from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = REPO_ROOT.parent
VAULT_ROOT = WORKSPACE_ROOT / "AegisDet Vault"
TASKS = VAULT_ROOT / "TASKS.md"
CURRENT_STATE = VAULT_ROOT / "CURRENT_STATE.md"
AUTO_STATE = VAULT_ROOT / "AUTO_STATE.md"
TASK_EVIDENCE = VAULT_ROOT / "TASK_EVIDENCE.md"
AUTO_LOG = VAULT_ROOT / "logs" / "auto-code-changes.md"
HUMAN_LOG = VAULT_ROOT / "logs" / "code-changes.md"
CODE_INVENTORY = VAULT_ROOT / "wiki" / "_code-inventory.generated.md"

AUTO_TASK_START = "<!-- AUTO-ACTIVITY:START -->"
AUTO_TASK_END = "<!-- AUTO-ACTIVITY:END -->"
AUTO_STATE_START = "<!-- AUTO-SYNC:START -->"
AUTO_STATE_END = "<!-- AUTO-SYNC:END -->"

TASK_PATTERN = re.compile(r"^- \[(?P<checked>[ xX])\] \*\*\[(?P<id>[A-Z0-9-]+)\]\*\* (?P<title>.+)$", re.MULTILINE)

TRACKED_AREAS = ("src", "scripts", "tests", "configs", "apps", "docs", ".github")
FORBIDDEN_SUFFIXES = {".pt", ".pth", ".onnx", ".engine", ".plan", ".ckpt", ".safetensors"}
SECRET_PATTERNS = (".env", "id_rsa", "credentials", "secrets")
MAX_STAGED_BYTES = 25 * 1024 * 1024


class SyncError(RuntimeError):
    pass


def run_git(*args: str, check: bool = False) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and proc.returncode != 0:
        raise SyncError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout.strip()


def now() -> str:
    return dt.datetime.now().astimezone().isoformat(timespec="seconds")


def replace_block(text: str, start: str, end: str, body: str) -> str:
    replacement = f"{start}\n{body.rstrip()}\n{end}"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(replacement, text, count=1)
    return text.rstrip() + "\n\n" + replacement + "\n"


def require_layout() -> None:
    required = [
        VAULT_ROOT,
        TASKS,
        CURRENT_STATE,
        VAULT_ROOT / "CONTEXT_LOCK.md",
        VAULT_ROOT / "wiki" / "_code-map.md",
        REPO_ROOT / "AGENTS.md",
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        raise SyncError("Missing required workspace paths:\n- " + "\n- ".join(missing))


def active_task() -> tuple[str, str] | None:
    text = TASKS.read_text(encoding="utf-8")
    for match in TASK_PATTERN.finditer(text):
        if match.group("checked").lower() != "x":
            task_id = match.group("id")
            title = match.group("title")
            if "DEFERRED" not in title and "OPTIONAL" not in title:
                return task_id, title
    return None


def git_state() -> dict[str, object]:
    inside = run_git("rev-parse", "--is-inside-work-tree") == "true"
    if not inside:
        return {
            "git_initialized": False,
            "branch": None,
            "commit": None,
            "dirty_files": [],
            "staged_files": [],
        }
    return {
        "git_initialized": True,
        "branch": run_git("branch", "--show-current") or "(detached)",
        "commit": run_git("rev-parse", "--short", "HEAD") or "(no commits)",
        "dirty_files": [x for x in run_git("status", "--porcelain").splitlines() if x],
        "staged_files": [x for x in run_git("diff", "--cached", "--name-only").splitlines() if x],
    }


def inventory() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for area in TRACKED_AREAS:
        base = REPO_ROOT / area
        if not base.exists():
            continue
        for p in sorted(base.rglob("*")):
            if not p.is_file() or "__pycache__" in p.parts or p.suffix == ".pyc":
                continue
            rel = p.relative_to(REPO_ROOT).as_posix()
            data = p.read_bytes()
            rows.append({
                "path": rel,
                "bytes": len(data),
                "sha256_12": hashlib.sha256(data).hexdigest()[:12],
            })
    return rows


def render_inventory(rows: list[dict[str, object]]) -> str:
    lines = [
        "# Generated Code Inventory",
        "",
        "_Generated by `aegisdet/tools/workspace_sync.py`; do not edit manually._",
        "",
        f"Generated: {now()}",
        "",
        "| Path | Bytes | SHA-256 prefix |",
        "|---|---:|---|",
    ]
    for row in rows:
        lines.append(f"| `{row['path']}` | {row['bytes']} | `{row['sha256_12']}` |")
    return "\n".join(lines) + "\n"


def update_generated_state(reason: str) -> dict[str, object]:
    require_layout()
    state = git_state()
    task = active_task()
    rows = inventory()
    sync_time = now()

    active_text = f"**{task[0]} — {task[1]}**" if task else "No unchecked non-deferred task found."
    dirty = state["dirty_files"]
    staged = state["staged_files"]

    auto_body = "\n".join([
        "## Automated workspace activity",
        "",
        f"- Last sync: `{sync_time}`",
        f"- Reason: `{reason}`",
        f"- Active task: {active_text}",
        f"- Git initialized: `{state['git_initialized']}`",
        f"- Branch: `{state['branch']}`",
        f"- Commit: `{state['commit']}`",
        f"- Dirty entries: `{len(dirty)}`",
        f"- Staged files: `{len(staged)}`",
        "",
        "This block is mechanical state. Use `workspace_sync.py record` for semantic progress or completion.",
    ])
    task_text = TASKS.read_text(encoding="utf-8")
    TASKS.write_text(replace_block(task_text, AUTO_TASK_START, AUTO_TASK_END, auto_body), encoding="utf-8")

    current_body = "\n".join([
        "## Automated code-workspace state",
        "",
        f"- Last sync: `{sync_time}`",
        f"- Reason: `{reason}`",
        f"- Active task: {active_text}",
        f"- Git branch: `{state['branch']}`",
        f"- Git commit: `{state['commit']}`",
        f"- Dirty entries: `{len(dirty)}`",
        f"- Staged files: `{len(staged)}`",
        f"- Generated code inventory files: `{len(rows)}`",
        "",
        "This section is generated and does not assert that an experiment or task is complete.",
    ])
    current_text = CURRENT_STATE.read_text(encoding="utf-8")
    CURRENT_STATE.write_text(replace_block(current_text, AUTO_STATE_START, AUTO_STATE_END, current_body), encoding="utf-8")

    payload = {
        "generated_at": sync_time,
        "reason": reason,
        "active_task": {"id": task[0], "title": task[1]} if task else None,
        "git": state,
        "inventory_count": len(rows),
    }
    AUTO_STATE.write_text(
        "# AUTO_STATE.md\n\n"
        "_Generated by the sibling code repository; do not edit manually._\n\n"
        "```json\n" + json.dumps(payload, indent=2) + "\n```\n",
        encoding="utf-8",
    )
    CODE_INVENTORY.write_text(render_inventory(rows), encoding="utf-8")
    return payload


def validate_staged_files() -> None:
    staged = [x for x in run_git("diff", "--cached", "--name-only").splitlines() if x]
    violations: list[str] = []
    for rel in staged:
        low = rel.lower()
        p = REPO_ROOT / rel
        if p.suffix.lower() in FORBIDDEN_SUFFIXES:
            violations.append(f"forbidden model/export file: {rel}")
        if any(token in low for token in SECRET_PATTERNS) and rel != ".env.example":
            violations.append(f"possible secret file: {rel}")
        if p.exists() and p.is_file() and p.stat().st_size > MAX_STAGED_BYTES:
            violations.append(f"file exceeds 25 MiB: {rel}")
    if violations:
        raise SyncError("Commit blocked:\n- " + "\n- ".join(violations))


def append_log(path: Path, heading: str, lines: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(f"# {heading}\n\n", encoding="utf-8")
    with path.open("a", encoding="utf-8") as f:
        f.write(f"\n## {now()}\n\n")
        for line in lines:
            f.write(f"- {line}\n")


def set_task_status(task_id: str, status: str) -> tuple[str, str]:
    text = TASKS.read_text(encoding="utf-8")
    found: tuple[str, str] | None = None

    def repl(match: re.Match[str]) -> str:
        nonlocal found
        if match.group("id") != task_id:
            return match.group(0)
        found = (match.group("id"), match.group("title"))
        checked = "x" if status == "complete" else match.group("checked")
        return f"- [{checked}] **[{match.group('id')}]** {match.group('title')}"

    new_text = TASK_PATTERN.sub(repl, text)
    if found is None:
        raise SyncError(f"Task ID not found: {task_id}")
    TASKS.write_text(new_text, encoding="utf-8")
    return found


def record(task_id: str, status: str, summary: str, verification: str, files: str | None) -> None:
    require_layout()
    task = set_task_status(task_id, status)
    commit = run_git("rev-parse", "--short", "HEAD") or "(no commit)"
    changed = files or run_git("status", "--short") or "(not supplied)"
    evidence = [
        f"### {task[0]} — {task[1]}",
        "",
        f"- Date: {now()}",
        f"- Status: {status}",
        f"- Code commit: `{commit}`",
        f"- Summary: {summary}",
        f"- Verification: {verification}",
        f"- Files/state: {changed}",
        "",
    ]
    with TASK_EVIDENCE.open("a", encoding="utf-8") as f:
        f.write("\n".join(evidence) + "\n")
    append_log(HUMAN_LOG, "Code Changes", [
        f"Task: {task_id}",
        f"Status: {status}",
        f"Summary: {summary}",
        f"Verification: {verification}",
        f"Commit: {commit}",
    ])
    update_generated_state(f"record:{task_id}:{status}")


def post_commit() -> None:
    payload = update_generated_state("post-commit")
    subject = run_git("log", "-1", "--pretty=%s") or "(unknown)"
    files = run_git("diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD") or "(none)"
    append_log(AUTO_LOG, "Automatic Code Activity Log", [
        f"Commit: {payload['git']['commit']}",
        f"Branch: {payload['git']['branch']}",
        f"Subject: {subject}",
        "Files: " + ", ".join(files.splitlines()),
    ])


def check() -> None:
    require_layout()
    state = update_generated_state("check")
    hooks_path = run_git("config", "--get", "core.hooksPath")
    print("AegisDet workspace check passed.")
    print(f"Repository: {REPO_ROOT}")
    print(f"Vault: {VAULT_ROOT}")
    print(f"Git initialized: {state['git']['git_initialized']}")
    print(f"Configured hooks path: {hooks_path or '(not configured)'}")
    task = state["active_task"]
    print(f"Active task: {task['id'] if task else '(none)'}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize AegisDet code state into its sibling vault.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_sync = sub.add_parser("sync")
    p_sync.add_argument("--reason", default="manual")

    sub.add_parser("check")
    sub.add_parser("pre-commit")
    sub.add_parser("post-commit")

    p_record = sub.add_parser("record")
    p_record.add_argument("--task", required=True)
    p_record.add_argument("--status", required=True, choices=("progress", "complete", "blocked"))
    p_record.add_argument("--summary", required=True)
    p_record.add_argument("--verification", required=True)
    p_record.add_argument("--files")

    args = parser.parse_args()
    try:
        if args.command == "sync":
            update_generated_state(args.reason)
        elif args.command == "check":
            check()
        elif args.command == "pre-commit":
            validate_staged_files()
            update_generated_state("pre-commit")
        elif args.command == "post-commit":
            post_commit()
        elif args.command == "record":
            record(args.task, args.status, args.summary, args.verification, args.files)
        return 0
    except SyncError as exc:
        print(f"AegisDet sync error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
